nutrient_patterns={
    "Total Fat": r"((Total\s*)?Fat\s*(\d+(\.\d+)?)\s*(g|mg|mcg|mog|µg|%)?|(Total\s*)?Fat\s*\((g|mg|mcg|mog|µg|%)\)\s*([a-zA-Z]|\d+(\.\d+)?)?)",
    # "Total Fatf2":r"(Total\s)?Fat\s*\((g|mg|mcg|mog|µg|%)\)\s*([a-zA-Z]|\d+(\.\d+)?)?",
    "Saturated Fat": r"(Saturated\s*Fat\s*([a-zA-Z]|\d+(\.\d+)?)\s*(g|mg|mcg|mog|µg|%)?|Saturated\s*fat\s*\((g|mg|mcg|mog|µg|%)\)\s*([a-zA-Z]|\d+(\.\d+)?)?)",
    # "Saturated fatf2":r"Saturated\s*fat\s*\((g|mg|mcg|mog|µg|%)\)\s*([a-zA-Z]|\d+(\.\d+)?)?",
    "Trans Fat": r"((t|T)rans\s*(f|F)at\s*([a-zA-Z]|\d+(\.\d+)?)\s*(g|mg|mcg|mog|µg|%)?|(t|T)rans\s*(f|F)at\s*\((g|mg|mcg|mog|µg|%)\)\s*([a-zA-Z]|\d+(\.\d+)?)?)",
    # "Transfatf2":r"Trans\s*fat\s*\((g|mg|mcg|mog|µg|%)\)\s*([a-zA-Z]|\d+(\.\d+)?)?",
    "Cholesterol": r"((Cholesterol|Cholestrol)\s*([a-zA-Z]|\d+(\.\d+)?)\s*(g|mg|mcg|mog|µg|%)?|(Cholesterol|Cholestrol)\s*\((g|mg|mcg|mog|µg|%)\)\s*([a-zA-Z]|\d+(\.\d+)?)?)",
    # "Cholesterolf2":r"Cholesterol\s*\((g|mg|mcg|mog|µg|%)\)\s*([a-zA-Z]|\d+(\.\d+)?)?",
    "Sodium": r"((S|s)odium\s*([a-zA-Z]|\d+(\.\d+)?)\s*(g|mg|mcg|mog|µg|%)?|(S|s)odium\s*\((g|mg|mcg|mog|µg|%)\)\s*([a-zA-Z]|\d+(\.\d+)?)?)",
    # "Sodiumf2":r"(S|s)odium\s*\((g|mg|mcg|mog|µg|%)\)\s*([a-zA-Z]|\d+(\.\d+)?)?",
    "Dietary Fiber": r"((Dietary\s*)?(f|F)iber\s*([a-zA-Z]|\d+(\.\d+)?)\s*(g|mg|mcg|mog|µg|%)?|(Dietary\s*)?((f|F)iber|(f|F)ibre)\s*\((g|mg|mcg|mog|µg|%)\)\s*([a-zA-Z]|\d+(\.\d+)?)?)",
    # "Dietary Fiberf2":r"(Dietary\s*)?((f|F)iber|(f|F)ibre)\s*\((g|mg|mcg|mog|µg|%)\)\s*([a-zA-Z]|\d+(\.\d+)?)?",
    # "Total Carb": r"(Total\s)?Carb?\s*([a-zA-Z]|\d+(\.\d+)?)\s*(g|mg|mcg|mog|µg|%)?",
    # "Total Carb.": r"(Total\s)Carb.?\s*([a-zA-Z]|\d+(\.\d+)?)\s*(g|mg|mcg|mog|µg|%)?",
    "Total Carbohydrate": r"((Total\s*)?(Carbohydrates?|Carb|Carb\.)\s*\((g|mg|mcg|mog|µg|%)\)\s*([a-zA-Z]|\d+(\.\d+)?)?|(Total\s*)?(Carbohydrates?|Carb|Carb\.)\s*([a-zA-Z]|\d+(\.\d+)?)\s*(g|mg|mcg|mog|µg|%)?)",
    # "Total Carbohydratef2":r"Total Carbohydrates?\s*\((g|mg|mcg|mog|µg|%)\)\s*([a-zA-Z]|\d+(\.\d+)?)?",
    "Total Sugars": r"((Total\s*)?Sugars?\s*([a-zA-Z]|\d+(\.\d+)?)\s*(g|mg|mcg|mog|µg|%)?|(Total\s*)?Sugars?\s*\((g|mg|mcg|mog|µg|%)\)\s*([a-zA-Z]|\d+(\.\d+)?)?)",
    # "Total Sugarsf2":r"(Total\s*)?Sugars?\s*\((g|mg|mcg|mog|µg|%)\)\s*([a-zA-Z]|\d+(\.\d+)?)?",
    "Protein": r"(Protein\s*([a-zA-Z]|\d+(\.\d+)?)\s*(g|mg|mcg|mog|µg|%)?|Protein\s*\((g|mg|mcg|mog|µg|%)\)\s*([a-zA-Z]|\d+(\.\d+)?)?)",
    # "Proteinf2":r'Protein\s*\((g|mg|mcg|mog|µg|%)\)\s*([a-zA-Z]|\d+(\.\d+)?)?',
    "Potassium": r"Potassium\s*([a-zA-Z]|\d+(\.\d+)?)\s*(g|mg|mcg|mog|µg|%)?",
    "Vitamin A": r"Vitamin A\s*([a-zA-Z]|\d+(\.\d+)?)\s*(g|mg|mcg|mog|µg|%)?",
    "Vitamin B6": r"Vitamin B6\s*([a-zA-Z]|\d+(\.\d+)?)\s*(g|mg|mcg|mog|µg|%)?",
    "Vitamin B12": r"Vitamin B12\s*([a-zA-Z]|\d+(\.\d+)?)\s*(g|mg|mcg|mog|µg|%)?",
    "Vitamin C": r"Vitamin C\s*([a-zA-Z]|\d+(\.\d+)?)\s*(g|mg|mcg|mog|µg|%)?",
    "Vitamin D": r"Vitamin D\s*([a-zA-Z]|\d+(\.\d+)?)\s*(g|mg|mcg|mog|µg|%)?",
    "Vitamin E": r"Vitamin E\s*([a-zA-Z]|\d+(\.\d+)?)\s*(g|mg|mcg|mog|µg|%)?",
    "Vitamin K": r"Vitamin K\s*([a-zA-Z]|\d+(\.\d+)?)\s*(g|mg|mcg|mog|µg|%)?",
    "Calcium": r"Calcium\s*([a-zA-Z]|\d+(\.\d+)?)\s*(g|mg|mcg|mog|µg|%)?",
    "Iron": r"Iron\s*([a-zA-Z]|\d+(\.\d+)?)\s*(g|mg|mcg|mog|µg|%)?"
}
nutrient_correction={
    # "Total Fatf2": "Total Fat",
    # "Saturated fatf2":"Saturated Fat",
    # "Transfatf2":"Trans Fat",
    # "Cholestrol":"Cholesterol",
    # "Cholesterolf2":"Cholesterol",
    # "Sodiumf2":"Sodium",
    # "Dietary Fiberf2":"Dietary Fiber",
    # "Total Carb":"Total Carbohydrate",
    # "Total Carb.":"Total Carbohydrate",
    # "Total Carbohydratef2":"Total Carbohydrate",
    # "Total Sugarsf2":"Total Sugars",
    # "Proteinf2":"Protein"
}
nutrients = [
"Total Fat",
"Saturated Fat",
"Trans Fat",
"Cholesterol",
"Sodium",
"Dietary Fiber",
"Total Carbohydrate",
"Total Sugars",
"Protein",
"Potassium",
"Vitamin A",
"Vitamin B6",
"Vitamin B12",
"Vitamin C",
"Vitamin D",
"Vitamin E",
"Vitamin K",
"Calcium",
"Iron"
]