nutrient_patterns={
    "Serving Size":r'\((\d+)(g|mg|ml)\)|\((\d+)\)',
    "Total Fat": r"(((total\s*)?fat|lipides?)\s*(\d+(\.\d+)?)\s*(g|mg|mcg|mog|µg|%)?|((total\s*)?fat|lipides?)\s*\((g|mg|mcg|mog|µg|%)\)\s*(\d+(\.\d+)?)?)",
    "Saturated Fat": r"(saturated\s*(fat|fatty\s*acids)\s*<?\s*(\d+(\.\d+)?)\s*(g|mg|mcg|mog|µg|%)?|saturated\s*(fat|fatty\s*acids)\s*\((g|mg|mcg|mog|µg|%)\)\s*(\d+(\.\d+)?)?|saturés?\s*\((g|mg|mcg|mog|µg|%)\)\s*(\d+(\.\d+)?)?|saturés?\s*<?\s*(\d+(\.\d+)?)\s*(g|mg|mcg|mog|µg|%)?)",
    "Poly Unsaturated Fat":r"(poly\s*unsaturated\s*(fat|fatty\s*acids)\s*<?\s*(\d+(\.\d+)?)\s*(g|mg|mcg|mog|µg|%)?|poly\s*unsaturated\s*(fat|fatty\s*acids)\s*\((g|mg|mcg|mog|µg|%)\)\s*(\d+(\.\d+)?)?)",
    "Mono Unsaturated Fat":r"(mono\s*unsaturated\s*(fat|fatty\s*acids)\s*<?\s*(\d+(\.\d+)?)\s*(g|mg|mcg|mog|µg|%)?|mono\s*unsaturated\s*(fat|fatty\s*acids)\s*\((g|mg|mcg|mog|µg|%)\)\s*(\d+(\.\d+)?)?)",
    "Trans Fat": r"(trans\s*((fat|fatty\s*acids))?\s*<?\s*(\d+(\.\d+)?)\s*(g|mg|mcg|mog|µg|%)?|trans\s*((fat|fatty\s*acids))?\s*\((g|mg|mcg|mog|µg|%)\)\s*(\d+(\.\d+)?)?)",
    "Cholesterol": r"((cholesterol|cholestrol|cholestérol)\s*<?\s*(\d+(\.\d+)?)\s*(g|mg|mcg|mog|µg|%)?|(cholesterol|cholestrol|cholestérol)\s*\((g|mg|mcg|mog|µg|%)\)\s*(\d+(\.\d+)?)?)",
    "Sodium": r"(sodium\s*<?\s*(\d+(\.\d+)?)\s*(g|mg|mcg|mog|µg|%)?|sodium\s*\((g|mg|mcg|mog|µg|%)\)\s*(\d+(\.\d+)?)?)",
    "Dietary Fiber": r"((dietary\s*)?(fiber|fibre)s?\s*<?\s*(\d+(\.\d+)?)\s*(g|mg|mcg|mog|µg|%)?|(dietary\s*)?(fiber|fibre)\s*\((g|mg|mcg|mog|µg|%)\)\s*(\d+(\.\d+)?)?)",
    "Total Carbohydrate": r"((total\s*)?(carbohydrates?|carb|carb\.)\s*\((g|mg|mcg|mog|µg|%)\)\s*(\d+(\.\d+)?)?|(total\s*)?(carbohydrates?|carb|carb\.)\s*<?\s*(\d+(\.\d+)?)\s*(g|mg|mcg|mog|µg|%)?)",
    "glucides":r"(glucides?\s*\((g|mg|mcg|mog|µg|%)\)\s*(\d+(\.\d+)?)?|(total\s*)?glucides?\s*<?\s*(\d+(\.\d+)?)\s*(g|mg|mcg|mog|µg|%)?)",
    "Total Sugars": r"((total\s*)?(sugars?|sucres)\s*<?\s*(\d+(\.\d+)?)\s*(g|mg|mcg|mog|µg|%)?|(total\s*)?(sugars?|sucres)\s*\((g|mg|mcg|mog|µg|%)\)\s*(\d+(\.\d+)?)?)",
    "Protein": r"(proteins?\s*<?\s*(\d+(\.\d+)?)\s*(g|mg|mcg|mog|µg|%)?|proteins?\s*\((g|mg|mcg|mog|µg|%)\)\s*(\d+(\.\d+)?)?|protéines?\s*\((g|mg|mcg|mog|µg|%)\)\s*(\d+(\.\d+)?)?|protéines?\s*<?\s*(\d+(\.\d+)?)\s*(g|mg|mcg|mog|µg|%)?)",
    "Potassium": r"(potassium\s*<?\s*(\d+(\.\d+)?)\s*(g|mg|mcg|mog|µg|%)?|potassium\s*\((g|mg|mcg|mog|µg|%)\)\s*(\d+(\.\d+)?)?)",
    "Vitamin A": r"(vitamin\s*a\s*<?\s*(\d+(\.\d+)?)\s*(g|mg|mcg|mog|µg|%)?|vitamin\s*a\s*\((g|mg|mcg|mog|µg|%)\)\s*(\d+(\.\d+)?)?)",
    "Vitamin B6": r"(vitamin\s*b6\s*<?\s*(\d+(\.\d+)?)\s*(g|mg|mcg|mog|µg|%)?|vitamin\s*b6\s*\((g|mg|mcg|mog|µg|%)\)\s*(\d+(\.\d+)?)?)",
    "Vitamin B12": r"(vitamin\s*b12\s*<?\s*(\d+(\.\d+)?)\s*(g|mg|mcg|mog|µg|%)?|vitamin\s*b12\s*\((g|mg|mcg|mog|µg|%)\)\s*(\d+(\.\d+)?)?)",
    "Vitamin C": r"(vitamin\s*c\s*<?\s*(\d+(\.\d+)?)\s*(g|mg|mcg|mog|µg|%)?|vitamin\s*c\s*\((g|mg|mcg|mog|µg|%)\)\s*(\d+(\.\d+)?)?)",
    "Vitamin D": r"(vitamin\s*d\s*<?\s*(\d+(\.\d+)?)\s*(g|mg|mcg|mog|µg|%)?|vitamin\s*d\s*\((g|mg|mcg|mog|µg|%)\)\s*(\d+(\.\d+)?)?)",
    "Vitamin E": r"(vitamin\s*e\s*<?\s*(\d+(\.\d+)?)\s*(g|mg|mcg|mog|µg|%)?|vitamin\s*e\s*\((g|mg|mcg|mog|µg|%)\)\s*(\d+(\.\d+)?)?)",
    "Vitamin K": r"(vitamin\s*k\s*<?\s*(\d+(\.\d+)?)\s*(g|mg|mcg|mog|µg|%)?|vitamin\s*k\s*\((g|mg|mcg|mog|µg|%)\)\s*(\d+(\.\d+)?)?)",
    "Calcium": r"(calcium\s*<?\s*(\d+(\.\d+)?)\s*(g|mg|mcg|mog|µg|%)?|calcium\s*\((g|mg|mcg|mog|µg|%)\)\s*(\d+(\.\d+)?)?)",
    "Iron": r"((i|f)ron\s*<?\s*(\d+(\.\d+)?)\s*(g|mg|mcg|mog|µg|%)?|(i|f)ron\s*\((g|mg|mcg|mog|µg|%)\)\s*(\d+(\.\d+)?)?)"
}
nutrient_correction={
    "glucides":"Total Carbohydrate",
}
nutrients = [
"Serving Size",
"Total Fat",
"Saturated Fat",
"Poly Unsaturated Fat",
"Mono Unsaturated Fat",
"Trans Fat",
"Cholesterol",
"Sodium",
"Dietary Fiber",
"Total Carbohydrate",
"Total Sugars",
"Protein",
"Potassium",
"Vitamin A",
"Vitamin B6",
"Vitamin B12",
"Vitamin C",
"Vitamin D",
"Vitamin E",
"Vitamin K",
"Calcium",
"Iron"
]